items = [

{
    "type": "Big kitchen knife",
    "label": "Big Kitchen Knife",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.500000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:15",
    "base_price": 30,
    "inventory": {"x": 1, "y": 2, "image": "weapons/big_kitchen_knife/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "Light and maneuverable in combat, but unfortunately not very effective in cutting through steel as well as quickly reaching the point of breaking if you try. Though, for sure better than hitting at metal with your bare fists.",
    "rotation_series": "weapons/big_kitchen_knife",
    "tux_part": "iso_big_kitchen_knife",
},

{
    "type": "Cutlass",
    "label": "Cutlass",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.550000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"dexterity": 20},
    "durability": "20:30",
    "base_price": 100,
    "inventory": {"x": 1, "y": 4, "image": "weapons/cutlass/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "Long reach while remaining maneuverable enough in combat to find the weak spots in droid armor are the advantages that partially makes up for the inability of a cutting blade to incur lots of damage on a heavily protected target. Repeatedly striking at metal quickly damages the blade though.",
    "rotation_series": "weapons/cutlass",
    "tux_part": "iso_cutlass",
},

{
    "type": "Antique Greatsword",
    "label": "Antique Greatsword",
    "slot": "weapon",
    "weapon": {
        "damage": 2,
        "attack_time": 1.000000,
        "reloading_time": 0.000000,
        "melee": True,
        "two_hand": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"strength": 25, "dexterity": 20},
    "durability": "20:30",
    "base_price": 400,
    "inventory": {"x": 2, "y": 5, "image": "weapons/sword/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "Very maneuverable for its size, and heavy enough to punch though weaker bot armor in 1 hit, the only real disadvantage of this old weapon is the same as for other swords. It just doesn't last long when cutting into metal parts.",
    "rotation_series": "weapons/sword",
    "tux_part": "iso_antique_greatsword",
},

{
    "type": "Chainsaw",
    "label": "Chainsaw",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 0.150000,
        "reloading_time": 0.000000,
        "melee": True,
        "two_hand": True,
        "motion_class": "2h_heavy_melee",
    },
    "requirements": {"strength": 20, "dexterity": 20},
    "durability": "6:8",
    "base_price": 500,
    "inventory": {"x": 2, "y": 4, "image": "weapons/chainsaw/inv_image.png" },
    "drop": {"class": "5", "sound": "drop_sword_sound.ogg"},
    "description": "Quite efficient at separating limbs from even a droid body, or digging through weaker armored parts to cause massive damage on internal electronics. But, the chain wears out very quickly when used on materials harder than wood, and supply shortages of new chains and other parts makes it expensive to maintain.",
    "rotation_series": "weapons/chainsaw",
    "tux_part": "iso_chainsaw",
},

{
    "type": "Meat cleaver",
    "label": "Meat Cleaver",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "30:40",
    "base_price": 50,
    "inventory": {"x": 2, "y": 2, "image": "weapons/meat_cleaver/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "Designed to chop through meat and bones, it's not as fragile as cutting blades when used against metal enemies. However, it is a bit slower and clumsier to use than more graceful weapons.",
    "rotation_series": "weapons/meat_cleaver",
    "tux_part": "iso_meat_cleaver",
},

{
    "type": "Small Axe",
    "label": "Small Axe",
    "slot": "weapon",
    "weapon": {
        "damage": 4,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"strength": 14, "dexterity": 15},
    "durability": "40:60",
    "base_price": 80,
    "inventory": {"x": 2, "y": 3, "image": "weapons/small_axe/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "While this axe was made for splitting wood, with some luck it can damage vital parts of a droid as well.",
    "rotation_series": "weapons/small_axe",
    "tux_part": "iso_small_axe",
},

{
    "type": "Large Axe",
    "label": "Large Axe",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 1.200000,
        "reloading_time": 0.000000,
        "melee": True,
        "two_hand": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"strength": 25, "dexterity": 18},
    "durability": "40:100",
    "base_price": 120,
    "inventory": {"x": 2, "y": 5, "image": "weapons/large_axe/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "While this weapon is somewhat slow and cumbersome to use, it is as good at leaving big dents in droids as it is at felling trees. A good hit is often capable of taking out lesser droids in a single hit.",
    "rotation_series": "weapons/large_axe",
    "tux_part": "iso_small_axe",
},

{
    "type": "Hunting knife",
    "label": "Hunting Knife",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.400000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "6:10",
    "base_price": 40,
    "inventory": {"x": 1, "y": 2, "image": "weapons/hunting_knife/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "A short stabbing dagger doesn't have much effect on the metal body of a droid, but with luck you might damage some wires or hoses in less protected areas, so it's still better than trying to take the machines on with bare hands.",
    "rotation_series": "weapons/hunting_knife",
    "tux_part": "iso_hunting_knife",
},

{
    "type": "Iron pipe",
    "label": "Iron Pipe",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.750000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "35:55",
    "base_price": 30,
    "inventory": {"x": 1, "y": 3, "image": "weapons/iron_pipe/inv_image.png" },
    "drop": {"class": "0:9", "sound": "drop_sword_sound.ogg"},
    "description": "A medium sized water pipe of iron can turn into an effective weapon even versus a metal opponent. While not likely to penetrate the armor of a bot, the impact force alone can still damage and shake loose circuit boards and weldings beneath the protective metal layer.",
    "rotation_series": "weapons/iron_pipe",
    "tux_part": "iso_iron_pipe",
},

{
    "type": "Big wrench",
    "label": "Big Wrench",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.750000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "30:50",
    "base_price": 60,
    "inventory": {"x": 1, "y": 3, "image": "weapons/big_wrench/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "A big heavy wrench can be surprisingly efficient in turning a bot into second hand parts, in a hands-on, brutal way if needed.",
    "rotation_series": "weapons/big_wrench",
    "tux_part": "iso_big_wrench",
},

{
    "type": "Crowbar",
    "label": "Crowbar",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"strength": 15},
    "durability": "45:65",
    "base_price": 60,
    "inventory": {"x": 1, "y": 3, "image": "weapons/crowbar/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "Something originally intended for breaking up doors or pulling out nails can also be used to break open droid skulls or give enough leverage to pull off their extremities.",
    "rotation_series": "weapons/crowbar",
    "tux_part": "iso_crowbar",
},

{
    "type": "Power hammer",
    "label": "Power Hammer",
    "slot": "weapon",
    "weapon": {
        "damage": 2,
        "attack_time": 0.250000,
        "reloading_time": 2.000000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": True,
        "ammunition": {"type": "Laser power pack", "clip": 60},
        "motion_class": "1hranged",
    },
    "durability": "30:40",
    "base_price": 250,
    "inventory": {"x": 2, "y": 3, "image": "weapons/power_hammer/inv_image.png" },
    "drop": {"class": "2:4", "sound": "drop_sword_sound.ogg"},
    "description": "The POWER NAIL DRIVER 3000 will, according to the advertisement, 'build your house for you'. While it's unclear how many nails your igloo will actually need, it sure can be handy nonetheless for bashing bot skulls. As long as the battery lasts, anyway.",
    "rotation_series": "weapons/power_hammer",
    "tux_part": "iso_power_hammer",
},

{
    "type": "Mace",
    "label": "Mace",
    "slot": "weapon",
    "weapon": {
        "damage": 3,
        "attack_time": 0.800000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"strength": 25, "dexterity": 15},
    "durability": "50:70",
    "base_price": 180,
    "inventory": {"x": 1, "y": 3, "image": "weapons/mace/inv_image.png" },
    "drop": {"class": "3:7", "sound": "drop_sword_sound.ogg"},
    "description": "The mace already proved on the medieval battlefield that it was good at crushing even heavily armored skulls. Unfortunately for the droids, this old knowledge still holds true.",
    "rotation_series": "weapons/mace",
    "tux_part": "iso_mace",
},

{
    "type": "Baseball bat",
    "label": "Baseball Bat",
    "slot": "weapon",
    "weapon": {
        "damage": 2,
        "attack_time": 0.700000,
        "reloading_time": 0.000000,
        "melee": True,
        "two_hand": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"strength": 12, "dexterity": 15},
    "durability": "10:15",
    "base_price": 30,
    "inventory": {"x": 2, "y": 4, "image": "weapons/baseball_bat/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "With 1-2 good two handed swings, a former droids head might fly far enough for you to score a home run. Just make sure to bring a backup weapon, because wooden bats have a predilection for splitting in two after too many hard hits.",
    "rotation_series": "weapons/baseball_bat",
    "tux_part": "iso_baseball_bat",
},

{
    "type": "Iron bar",
    "label": "Iron Bar",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 1.000000,
        "reloading_time": 0.000000,
        "melee": True,
        "two_hand": True,
        "motion_class": "2h_heavy_melee",
    },
    "requirements": {"strength": 20, "dexterity": 15},
    "durability": "60:75",
    "base_price": 70,
    "inventory": {"x": 1, "y": 5, "image": "weapons/iron_bar/inv_image.png" },
    "drop": {"class": "2:6", "sound": "drop_sword_sound.ogg"},
    "description": "A bit slow and cumbersome to use, and prohibiting the security of a shield to cower behind, this weapon isn't always a good option. But if you do hit, you are sure to do more damage than just a scratch.",
    "rotation_series": "weapons/iron_bar",
    "tux_part": "iso_iron_bar",
},

{
    "type": "Sledgehammer",
    "label": "Sledgehammer",
    "slot": "weapon",
    "weapon": {
        "damage": 8,
        "attack_time": 1.500000,
        "reloading_time": 0.000000,
        "melee": True,
        "two_hand": True,
        "motion_class": "2h_heavy_melee",
    },
    "requirements": {"strength": 25, "dexterity": 20},
    "durability": "40:60",
    "base_price": 150,
    "inventory": {"x": 2, "y": 5, "image": "weapons/sledgehammer/inv_image.png" },
    "drop": {"class": "0", "sound": "drop_sword_sound.ogg"},
    "description": "Very slow and only for the strongest wielder, but only the tougher droids can survive more than 1-2 direct hits.",
    "rotation_series": "weapons/sledgehammer",
    "tux_part": "iso_sledgehammer",
},

{
    "type": "Light saber",
    "label": "Light Saber",
    "slot": "weapon",
    "weapon": {
        "damage": 20,
        "attack_time": 0.500000,
        "reloading_time": 2.000000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": True,
        "ammunition": {"type": "Laser power pack", "clip": 20},
        "two_hand": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"dexterity": 30},
    "durability": "1000:1000",
    "base_price": 1500,
    "inventory": {"x": 1, "y": 2, "image": "weapons/light_saber/inv_image.png" },
    "drop": {"class": "7:9", "sound": "drop_sword_sound.ogg"},
    "description": "In the hands of a true master, this excellent technological craftsmanship is as deadly as it is beautiful. It requires laser crystals to work properly.",
    "rotation_series": "weapons/light_saber",
    "tux_part": "iso_sword",
},

{
    "type": "Laser staff",
    "label": "Laser Staff",
    "slot": "weapon",
    "weapon": {
        "damage": 25,
        "attack_time": 0.400000,
        "reloading_time": 2.000000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": True,
        "ammunition": {"type": "Laser power pack", "clip": 20},
        "motion_class": "1hmelee",
    },
    "requirements": {"dexterity": 40},
    "durability": "1000:1000",
    "base_price": 2000,
    "inventory": {"x": 1, "y": 3, "image": "weapons/laser_staff/inv_image.png" },
    "drop": {"class": "8:9", "sound": "drop_sword_sound.ogg"},
    "description": "A close combat master with this weapon in his hands is a pure whirling dervish of death. It requires laser crystals to work properly.",
    "rotation_series": "weapons/laser_staff",
    "tux_part": "iso_sword",
},

{
    "type": "Nobody's edge",
    "label": "Nobody's Edge",
    "slot": "weapon",
    "weapon": {
        "damage": 40,
        "attack_time": 0.500000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "base_price": 0,
    "inventory": {"x": 1, "y": 2, "image": "weapons/laser_dagger/inv_image.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "This blade pulses with evil. That power. That energy. Nothing can stop you now.",
    "rotation_series": "weapons/laser_dagger",
    "tux_part": "iso_hunting_knife",
},

{
    "type": "Laser Scalpel",
    "label": "Laser Scalpel",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.500000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "base_price": 50,
    "inventory": {"x": 1, "y": 1, "image": "weapons/laser_dagger/inv_image.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "I murdered the only person within a thousand miles who can heal me, and all I got was this lousy scalpel.",
    "rotation_series": "weapons/laser_dagger",
    "tux_part": "iso_hunting_knife",
},

{
    "type": "Shock knife",
    "label": "Shock Knife",
    "slot": "weapon",
    "weapon": {
        "damage": 30,
        "attack_time": 0.500000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "base_price": 0,
    "inventory": {"x": 1, "y": 2, "image": "weapons/shock_knife/inv_image.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "FIXME and all values",
    "rotation_series": "weapons/shock_knife",
    "tux_part": "iso_shock_knife",
},

{
    "type": "Energy whip",
    "label": "Energy Whip",
    "slot": "weapon",
    "weapon": {
        "damage": 30,
        "attack_time": 0.500000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "base_price": 0,
    "inventory": {"x": 2, "y": 2, "image": "weapons/energy_whip/inv_image.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "FIXME and all values",
    "rotation_series": "weapons/energy_whip",
    "tux_part": "iso_energy_whip",
},

{
    "type": ".22 Automatic",
    "label": ".22 Automatic",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.300000,
        "reloading_time": 2.700000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "half_pulse", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": ".22 LR Ammunition", "clip": 11},
        "motion_class": "1hranged",
    },
    "durability": "70:80",
    "base_price": 150,
    "inventory": {"x": 1, "y": 2, "image": "weapons/22_automatic/inv_image.png" },
    "drop": {"class": "0", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "With .22 ammo, it's mostly dumb luck if you actually damage a bot with this pistol. On the bright side, you will get a LOT of target practice out of each bot before a bullet or two manages to find a weak enough spot to take the bot out.",
    "rotation_series": "weapons/22_automatic",
    "tux_part": "iso_22_automatic",
},

{
    "type": ".22 Hunting Rifle",
    "label": ".22 Hunting Rifle",
    "slot": "weapon",
    "weapon": {
        "damage": 2,
        "attack_time": 0.750000,
        "reloading_time": 5.250000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "half_pulse", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": ".22 LR Ammunition", "clip": 11},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "70:80",
    "base_price": 250,
    "inventory": {"x": 1, "y": 5, "image": "weapons/22_rifle/inv_image.png" },
    "drop": {"class": "0", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "A .22 hunting rifle was mainly used for sports shooting and for cheap training. As a hunting weapon its main use was to kill small vermin such as rats and squirrels. It was also highly effective against rabbits. Unfortunately, you won't be hunting 'wabbits'...",
    "rotation_series": "weapons/22_rifle",
    "tux_part": "iso_22_hunting_rifle",
},

{
    "type": "Two Barrel sawn off shotgun",
    "label": "Two Barrel Sawn Off Shotgun",
    "slot": "weapon",
    "weapon": {
        "damage": 3,
        "attack_time": 0.200000,
        "reloading_time": 2.800000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "shotgun", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Shotgun shells", "clip": 2},
        "motion_class": "1hranged",
    },
    "durability": "50:60",
    "base_price": 200,
    "inventory": {"x": 2, "y": 2, "image": "weapons/shotgun_sawn_off/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Often wielded in the past by thugs or convenience store owners, this little baby is less powerful than the two-handed model, but makes up for it by letting you use a shield in conjunction with it.",
    "rotation_series": "weapons/shotgun_sawn_off",
    "tux_part": "iso_shotgun_sawn_off",
},

{
    "type": "Two Barrel shotgun",
    "label": "Two Barrel Shotgun",
    "slot": "weapon",
    "weapon": {
        "damage": 2,
        "attack_time": 0.200000,
        "reloading_time": 3.800000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "shotgun", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Shotgun shells", "clip": 2},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "50:60",
    "base_price": 250,
    "inventory": {"x": 2, "y": 4, "image": "weapons/shotgun_2_barrel/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "An old standby of farmers and bird hunters. While capable of causing a fair amount of damage to droid armor, the limited rounds capacity and fairly slow reloading time make this weapon preferable to melee weapons, but only just. Requires two hands to wield.",
    "rotation_series": "weapons/shotgun_2_barrel",
    "tux_part": "iso_shotgun",
},

{
    "type": "Pump action shotgun",
    "label": "Pump Action Shotgun",
    "slot": "weapon",
    "weapon": {
        "damage": 2,
        "attack_time": 0.750000,
        "reloading_time": 3.2500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "shotgun", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Shotgun shells", "clip": 8},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "45:55",
    "base_price": 300,
    "inventory": {"x": 2, "y": 4, "image": "weapons/shotgun_pump/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "The pump action shotgun isn't quite as powerful as the double barrel equivalent, but it does hold more ammo per clip. Requires two hands to wield.",
    "rotation_series": "weapons/shotgun_pump",
    "tux_part": "iso_shotgun",
},

{
    "type": "9mm Automatic",
    "label": "9mm Automatic",
    "slot": "weapon",
    "weapon": {
        "damage": 4,
        "attack_time": 0.500000,
        "reloading_time": 2.500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "half_pulse", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": "9x19mm Ammunition", "clip": 19},
        "motion_class": "1hranged",
    },
    "durability": "50:60",
    "base_price": 400,
    "inventory": {"x": 2, "y": 1, "image": "weapons/9mm_pistol/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Nine millimeter ammo is a common caliber. While not very powerful, it allows for more rounds per clip than bigger ammunition.",
    "rotation_series": "weapons/9mm_pistol",
    "tux_part": "iso_9mm_pistol",
},

{
    "type": "9mm Sub Machine Gun",
    "label": "9mm Sub Machine Gun",
    "slot": "weapon",
    "weapon": {
        "damage": 3,
        "attack_time": 0.200000,
        "reloading_time": 2.800000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "half_pulse", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": "9x19mm Ammunition", "clip": 30},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "60:70",
    "base_price": 950,
    "inventory": {"x": 2, "y": 3, "image": "weapons/9mm_smg/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "These are commonly referred to as bullet hoses.",
    "rotation_series": "weapons/9mm_smg",
    "tux_part": "iso_9mm_sub_machine_gun",
},

{
    "type": "7.62mm Hunting Rifle",
    "label": "7.62mm Hunting Rifle",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 0.800000,
        "reloading_time": 4.200000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "half_pulse", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": "7.62x39mm Ammunition", "clip": 5},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "50:60",
    "base_price": 800,
    "inventory": {"x": 2, "y": 5, "image": "weapons/7_62mm_hunting_rifle/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "7.62 millimeter ammo is commonly used in assault rifles. This is a more civilian take on that concept.",
    "rotation_series": "weapons/7_62mm_hunting_rifle",
    "tux_part": "iso_7_62mm_hunting_rifle",
},

{
    "type": "7.62mm AK-47",
    "label": "7.62mm AK-47",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 0.200000,
        "reloading_time": 2.800000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "half_pulse", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": "7.62x39mm Ammunition", "clip": 30},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "70:80",
    "base_price": 1400,
    "inventory": {"x": 2, "y": 4, "image": "weapons/7_62mm_ak47/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "The favorite weapon of third-world countries everywhere, this is a mass-produced, fairly reliable automatic weapon.",
    "rotation_series": "weapons/7_62mm_ak47",
    "tux_part": "iso_7_62mm_ak47",
},

{
    "type": "Barrett M82 Sniper Rifle",
    "label": "Barrett M82 Sniper Rifle",
    "slot": "weapon",
    "weapon": {
        "damage": 10,
        "attack_time": 1.200000,
        "reloading_time": 2.800000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "single", "speed": 30.000000, "lifetime": -1.000000},
        "ammunition": {"type": ".50 BMG (12.7x99mm) Ammunition", "clip": 10},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "requirements": {"strength": 24},
    "durability": "40:50",
    "base_price": 2000,
    "inventory": {"x": 2, "y": 5, "image": "weapons/50_barrett_m82/inv_image.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Powerful enough to stop a truck, literally, the likelihood of even a battle droid surviving more than 2 hits by this weapon is quite slim. It doesn't even matter if the pesky droid is cowering behind a wall, the bullets will break right through and make the bot ready for the scrap heap in no time.",
    "rotation_series": "weapons/50_barrett_m82",
    "tux_part": "iso_barrett_m82_sniper_rifle",
},

{
    "type": "Laser pistol",
    "label": "Laser Pistol",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 0.400000,
        "reloading_time": 2.600000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "laser_rifle", "speed": 90.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 20},
        "motion_class": "1hranged",
    },
    "durability": "100:110",
    "base_price": 500,
    "inventory": {"x": 2, "y": 1, "image": "weapons/laser_pistol/inv_image.png" },
    "drop": {"class": "6:8", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "A basic laser, but it has good uses in certain situations. No warranty of any kind, though.",
    "rotation_series": "weapons/laser_pistol",
    "tux_part": "iso_laser_pistol",
},

{
    "type": "Laser Rifle",
    "label": "Laser Rifle",
    "slot": "weapon",
    "weapon": {
        "damage": 8,
        "attack_time": 0.600000,
        "reloading_time": 3.400000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "laser_rifle", "speed": 90.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 40},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "100:110",
    "base_price": 1000,
    "inventory": {"x": 1, "y": 4, "image": "weapons/laser_rifle/inv_image.png" },
    "drop": {"class": "7:9", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "This rifle is a high-end laser weapon. There is only one problem with it: Shooting it is too much fun. People often end up with no ammunition in the middle of a battle.",
    "rotation_series": "weapons/laser_rifle",
    "tux_part": "iso_laser_rifle",
},

{
    "type": "Laser Pulse Rifle",
    "label": "Laser Pulse Rifle",
    "slot": "weapon",
    "weapon": {
        "damage": 4,
        "attack_time": 0.150000,
        "reloading_time": 2.8500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "laser_rifle", "speed": 90.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 60},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "140:160",
    "base_price": 1000,
    "inventory": {"x": 2, "y": 4, "image": "weapons/laser_pulse_rifle/inv_image.png" },
    "drop": {"class": "7:9", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "The pulse laser technology, allowing for many repeated short bursts without the weapon overheating, makes this quite a useful weapon. The damage from each shot is noticeably less than from a Laser rifle, but the firing rate more than makes up for it.",
    "rotation_series": "weapons/laser_pulse_rifle",
    "tux_part": "iso_laser_pulse_rifle",
},

{
    "type": "Laser Pulse Cannon",
    "label": "Laser Pulse Cannon",
    "slot": "weapon",
    "weapon": {
        "damage": 6,
        "attack_time": 0.150000,
        "reloading_time": 3.8500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "military", "speed": 90.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 80},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "requirements": {"strength": 28},
    "durability": "140:160",
    "base_price": 2000,
    "inventory": {"x": 4, "y": 4, "image": "weapons/laser_pulse_cannon/inv_image.png" },
    "drop": {"class": "8:9", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "The pulse laser technology, allowing for many repeated short bursts without the weapon overheating, combined with a military design makes this weapon the preferred choice for most soldiers. Its quick no-recoil firing, large magazine, and awesome killing power makes it the ideal weapon for cleansing large droid infestations in mere minutes.",
    "rotation_series": "weapons/laser_pulse_cannon",
    "tux_part": "iso_laser_pulse_cannon",
},

{
    "type": "Plasma pistol",
    "label": "Plasma Pistol",
    "slot": "weapon",
    "weapon": {
        "damage": 12,
        "attack_time": 0.750000,
        "reloading_time": 2.2500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "plasma_white", "speed": 15.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Plasma energy container", "clip": 6},
        "motion_class": "1hranged",
    },
    "durability": "30:40",
    "base_price": 750,
    "inventory": {"x": 2, "y": 2, "image": "weapons/plasma_pistol/inv_image.png" },
    "drop": {"class": "6:8", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "The basic plasma weapon in a conveniently small package.",
    "rotation_series": "weapons/plasma_pistol",
    "tux_part": "iso_plasma_pistol",
},

{
    "type": "Plasma Gun",
    "label": "Plasma Gun",
    "slot": "weapon",
    "weapon": {
        "damage": 20,
        "attack_time": 1.000000,
        "reloading_time": 4.000000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "plasma_white", "speed": 1.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Plasma energy container", "clip": 12},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "30:40",
    "base_price": 1200,
    "inventory": {"x": 2, "y": 3, "image": "weapons/plasma_gun/inv_image2.png" },
    "drop": {"class": "7:9", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "A somewhat slow weapon, but once you do hit plenty a bot will just down on the spot. A good alternative to a pulse laser for the skilled marksman.",
    "rotation_series": "weapons/plasma_gun",
    "tux_part": "iso_gun1",
},

{
    "type": "Exterminator",
    "label": "Exterminator",
    "slot": "weapon",
    "weapon": {
        "damage": 40,
        "attack_time": 0.5000000,
        "reloading_time": 4.500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "exterminator", "speed": 0.2500000, "lifetime": -1.000000},
        "ammunition": {"type": "2 mm Exterminator Ammunition", "clip": 2},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "40:50",
    "base_price": 1000,
    "inventory": {"x": 2, "y": 2, "image": "weapons/exterminator_simple/inv_image.png" },
    "drop": {"class": "8:9", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "While this weapon is capable of firing really powerful shots, beware of the exceptionally long reloading times. (Don't get swarmed by enemies with this weapon unless you have powerful armor!)",
    "rotation_series": "weapons/exterminator_simple",
    "tux_part": "iso_exterminator",
},

{
    "type": "The Super Exterminator!!!",
    "label": "The Super Exterminator!!!",
    "slot": "weapon",
    "weapon": {
        "damage": 90,
        "attack_time": 0.500000,
        "reloading_time": 4.500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "exterminator", "speed": 3.000000, "lifetime": -1.000000},
        "ammunition": {"type": "2 mm Exterminator Ammunition", "clip": 2},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "30:40",
    "base_price": 3000,
    "inventory": {"x": 2, "y": 3, "image": "weapons/exterminator_simple/inv_image2.png" },
    "drop": {"class": "9", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "This bad boy is known to blow away most enemies with a single blast. A dangerous weapon that you don't want to be on the receiving end of.",
    "rotation_series": "weapons/exterminator_simple",
    "tux_part": "iso_exterminator",
},

{
    "type": "Electro Laser Rifle",
    "label": "Electro Laser Rifle",
    "slot": "weapon",
    "weapon": {
        "damage": 50,
        "attack_time": 1.500000,
        "reloading_time": 3.500000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "exterminator", "speed": 70.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 8},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "30:40",
    "base_price": 3000,
    "inventory": {"x": 2, "y": 5, "image": "weapons/electro_laser_rifle/inv_image.png" },
    "drop": {"class": "9", "sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "A specialized beam of laser momentarily ionizes the air between the target and the gun, turning it into highly conductive plasma. Milliseconds later, a powerful electric shock is delivered through the air and hits the target. This weapon is effective against people as it is against bots, and indeed few are the droid classes that can withstand more than a few hits from it before going down. The one downside is the enormous power consumption that makes this weapon expensive to maintain.",
    "rotation_series": "weapons/electro_laser_rifle",
    "tux_part": "iso_electro_laser_rifle",
},

{
    "type": "Book 1",
    "label": "Source Book of Emergency Shutdown",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Emergency shutdown"},
    "base_price": 500,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_green.png" },
    "drop": {"class": "2:9", "sound": "drop_book_sound.ogg"},
    "description": "Everyone needs to blow off some steam every now and then.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 2",
    "label": "Source Book of Check System Integrity",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Check system integrity"},
    "base_price": 250,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_white.png" },
    "drop": {"class": "2:9", "sound": "drop_book_sound.ogg"},
    "description": "An incredible healing program, probably the only one you will ever need.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 3",
    "label": "Source Book of Sanctuary",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Sanctuary"},
    "base_price": 450,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_green.png" },
    "drop": {"sound": "drop_book_sound.ogg"},
    "description": "The art of rapidly moving away from danger is very useful. Even when used in reverse, it has its uses.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 4",
    "label": "Source Book of Malformed Packet",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Malformed packet"},
    "base_price": 300,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_purple.png" },
    "drop": {"class": "2:9", "sound": "drop_book_sound.ogg"},
    "description": "When computers are presented with the unexpected, they can damage themselves.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 5",
    "label": "Source Book of Calculate Pi",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Calculate Pi"},
    "base_price": 300,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_orange.png" },
    "drop": {"class": "2:9", "sound": "drop_book_sound.ogg"},
    "description": "It is not a big problem to make a badly designed system to go hunting for the impossible, causing a performance impact.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 6",
    "label": "Source Book of Blue Screen",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Blue Screen"},
    "base_price": 300,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_blue.png" },
    "drop": {"class": "3:9", "sound": "drop_book_sound.ogg"},
    "description": "With a little touch a war machine comes crashing to a halt. For a while.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 7",
    "label": "Source Book of Broadcast Blue Screen",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Broadcast Blue Screen"},
    "base_price": 900,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_blue.png" },
    "drop": {"class": "5:9", "sound": "drop_book_sound.ogg"},
    "description": "With a little touch a war machine comes crashing to a halt. For a while.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 8",
    "label": "Source Book of Invisibility",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Invisibility"},
    "base_price": 600,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_green.png" },
    "drop": {"class": "4:9", "sound": "drop_book_sound.ogg"},
    "description": "I am not the Linarian you are looking for.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 9",
    "label": "Source Book of Virus",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Virus"},
    "base_price": 450,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_red.png" },
    "drop": {"class": "4:9", "sound": "drop_book_sound.ogg"},
    "description": "This is not just a firmware upgrade, my dear bot. You are about to find out what exactly I want to give you.",
    "rotation_series": "spellbook",
},

{
    "type": "Book 10",
    "label": "Source Book of Broadcast Virus",
    "right_use": {"tooltip": "Permanently acquire/enhance this program", "add_skill": "Broadcast virus"},
    "base_price": 1350,
    "inventory": {"x": 2, "y": 2, "image": "spellbook/inv_image_red.png" },
    "drop": {"class": "6:9", "sound": "drop_book_sound.ogg"},
    "description": "The network is wide and dangerous. Many traps await the weak and unprepared.",
    "rotation_series": "spellbook",
},

{
    "type": "NPC Hand to hand weapon",
    "label": "NPC Hand to Hand Weapon",
    "slot": "weapon",
    "weapon": {
        "damage": 3,
        "attack_time": 0.450000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "35:45",
    "base_price": 350,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Bot use only",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 123 Weak Robotic Arm",
    "label": "Droid 123 Weak Robotic Arm",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.950000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "20:30",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "Item_Drop_Sound_0.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "NONE_AVAILABLE_YET",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 139 Plasma Trash Vaporiser",
    "label": "Droid 139 Plasma Trash Vaporiser",
    "slot": "weapon",
    "weapon": {
        "damage": 2,
        "attack_time": 1.000000,
        "reloading_time": 6.6500000,
        "melee": False,
        "bullet": {"type": "plasma_white", "speed": 1.000000, "lifetime": 2.000000},
        "ammunition": {"type": "Plasma energy container", "clip": 3},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "10:20",
    "base_price": 40,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_ranged.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "NONE_AVAILABLE_YET",
    "tux_part": "iso_gun1",
},

{
    "type": "Droid 247 Robotic Arm",
    "label": "Droid 247 Robotic Arm",
    "slot": "weapon",
    "weapon": {
        "damage": 3,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 249 Pulse Laser Welder",
    "label": "Droid 249 Pulse Laser Welder",
    "slot": "weapon",
    "weapon": {
        "damage": 1,
        "attack_time": 0.150000,
        "reloading_time": 4.8500000,
        "melee": False,
        "bullet": {"type": "half_pulse", "speed": 2.000000, "lifetime": 2.00000},
        "ammunition": {"type": "Laser power pack", "clip": 15},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "10:20",
    "base_price": 100,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_ranged.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "NONE_AVAILABLE_YET",
    "tux_part": "iso_gun1",
},

{
    "type": "Droid 296 Plasmabeam Cutter",
    "label": "Droid 296 Plasmabeam Cutter",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 302 Overcharged Barcode Reader",
    "label": "Droid 302 Overcharged Barcode Reader",
    "slot": "weapon",
    "weapon": {
        "damage": 5,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 329 Dual Overcharged Barcode Reader",
    "label": "Droid 329 Dual Overcharged Barcode Reader",
    "slot": "weapon",
    "weapon": {
        "damage": 8,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 420 Laser Scalpel",
    "label": "Droid 420 Laser Scalpel",
    "slot": "weapon",
    "weapon": {
        "damage": 10,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 476 Small Laser",
    "label": "Droid 476 Small Laser",
    "slot": "weapon",
    "weapon": {
        "damage": 4,
        "attack_time": 1.200000,
        "reloading_time": 1.200000,
        "melee": False,
        "bullet": {"type": "single", "speed": 4.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 5},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "10:20",
    "base_price": 250,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_ranged.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "NONE_AVAILABLE_YET",
    "tux_part": "iso_gun1",
},

{
    "type": "Droid 493 Power Hammer",
    "label": "Droid 493 Power Hammer",
    "slot": "weapon",
    "weapon": {
        "damage": 10,
        "attack_time": 6.00000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 516 Robotic Fist",
    "label": "Droid 516 Robotic Fist",
    "slot": "weapon",
    "weapon": {
        "damage": 12,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 543 Tree Harvester",
    "label": "Droid 543 Tree Harvester",
    "slot": "weapon",
    "weapon": {
        "damage": 8,
        "attack_time": 0.100000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 571 Robotic Fist",
    "label": "Droid 571 Robotic Fist",
    "slot": "weapon",
    "weapon": {
        "damage": 15,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 598 Robotic Fist",
    "label": "Droid 598 Robotic Fist",
    "slot": "weapon",
    "weapon": {
        "damage": 18,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "durability": "10:20",
    "base_price": 120,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_melee.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_sword_yellow",
    "tux_part": "iso_sword",
},

{
    "type": "Droid 7xx Tux Seeking Missiles",
    "label": "Droid 7xx Tux Seeking Missiles",
    "slot": "weapon",
    "weapon": {
        "damage": 15,
        "attack_time": 1.200000,
        "reloading_time": 0.800000,
        "melee": False,
        "bullet": {"type": "single", "speed": 16.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 30},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "10:20",
    "base_price": 250,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_ranged.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "NONE_AVAILABLE_YET",
    "tux_part": "iso_gun1",
},

{
    "type": "Droid Advanced Twin Laser",
    "label": "Droid Advanced Twin Laser",
    "slot": "weapon",
    "weapon": {
        "damage": 15,
        "attack_time": 1.400000,
        "reloading_time": 2.600000,
        "melee": False,
        "bullet": {"type": "military", "speed": 60.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 30},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "requirements": {"strength": 30, "dexterity": 40},
    "durability": "10:20",
    "base_price": 800,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_ranged.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/laser_pulse_rifle",
    "tux_part": "iso_gun1",
},

{
    "type": "Droid 883 Exterminator",
    "label": "Droid 883 Exterminator",
    "slot": "weapon",
    "weapon": {
        "damage": 10,
        "attack_time": 1.00000,
        "reloading_time": 3.000000,
        "melee": False,
        "bullet": {"type": "exterminator", "speed": 4.000000, "lifetime": -1.000000},
        "ammunition": {"type": "2 mm Exterminator Ammunition", "clip": 2},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "requirements": {"strength": 20, "dexterity": 45},
    "durability": "10:20",
    "base_price": 1001,
    "inventory": {"x": 2, "y": 2, "image": "weapons/bot_ranged.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "Droid weaponry",
    "rotation_series": "weapons/exterminator_simple",
    "tux_part": "iso_gun1",
},

{
    "type": "Autogun Laser Pistol",
    "label": "Autogun Laser Pistol",
    "slot": "weapon",
    "weapon": {
        "damage": 3,
        "attack_time": 1.100000,
        "reloading_time": 0.000000,
        "reloading_sound": "effects/item_sounds/Item_Range_Weapon_Put_Sound_0.ogg",
        "melee": False,
        "bullet": {"type": "laser_rifle", "speed": 50.000000, "lifetime": -1.000000},
        "ammunition": {"type": "Laser power pack", "clip": 1},
        "motion_class": "1hranged",
    },
    "durability": "100:110",
    "base_price": 500,
    "inventory": {"x": 1, "y": 1, "image": "weapons/bot_ranged.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "This is the laser weapon of the autogun. If you see this item whilst normal gameplay, please make a bugreport.",
    "rotation_series": "weapons/laser_pistol",
    "tux_part": "iso_laser_pistol",
},

{
    "type": "Cheat Gun",
    "label": "Cheat Gun",
    "slot": "weapon",
    "weapon": {
        "damage": 9999,
        "attack_time": 0.100000,
        "reloading_time": 0.000000,
        "melee": False,
        "bullet": {"type": "plasma_white", "speed": 200.000000, "lifetime": -1.000000},
        "two_hand": True,
        "motion_class": "2hranged",
    },
    "durability": "16000:16001",
    "base_price": 10000,
    "inventory": {"x": 2, "y": 3, "image": "weapons/plasma_gun/inv_image2.png" },
    "drop": {"sound": "Item_Range_Weapon_Put_Sound_0.ogg"},
    "description": "This item is used by testers. If you find it ingame without using a cheat, please report it as a bug.",
    "rotation_series": "weapons/plasma_gun",
    "tux_part": "iso_gun1",
},

{
    "type": "Small Tutorial Axe",
    "label": "Small Tutorial Axe",
    "slot": "weapon",
    "weapon": {
        "damage": 3,
        "attack_time": 0.600000,
        "reloading_time": 0.000000,
        "melee": True,
        "motion_class": "1hmelee",
    },
    "requirements": {"strength": 14, "dexterity": 15},
    "durability": "40:60",
    "base_price": 80,
    "inventory": {"x": 2, "y": 3, "image": "weapons/small_axe/inv_image_tutorial.png" },
    "drop": {"sound": "drop_sword_sound.ogg"},
    "description": "While this axe was made for splitting wood, with some luck it can damage vital parts of a droid as well.",
    "rotation_series": "weapons/small_axe",
    "tux_part": "iso_small_axe",
}
]
